version: "3"

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: on-failure
    env_file: .venv
    ports:
      - "80:5000"
    volumes:
      - ./app:/app
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis-data:/data
    ports:
      - "6379:6379"